apiVersion: v1
kind: Service
metadata:
  name: nexgate
  labels: 
    app: nexgate
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 9999
    name: http
  selector:  
    app: nexgate

