apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexgate
  labels: 
    app: nexgate
    version: v1
  namespace: nexclipper
spec:
  replicas: 1
  template:
    metadata:
      name: nexgate
      labels:
        app: nexgate
    spec:
      containers:
        - name: nexgate
          image: nexclipper/nexgate:k8s-v0.1
          ports:
            - containerPort: 9999
              name: nexgate
