apiVersion: v1
kind: Service
metadata:
  name: workflow
  labels: 
    app: workflow
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 9000
    name: http
  selector:  
    app: workflow
