apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow
  labels: 
    app: workflow
    version: v1
  namespace: nexclipper
spec:
  replicas: 1
  template:
    metadata:
      name: workflow
      labels:
        app: workflow
    spec:
      containers:
        - name: workflow
          image: nexclipper/nexworkflow:k8s-v0.1
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: workflow
          env:
            - name: KAFKA_ZOOKEEPER
              value: "kafka-zookeeper.kafka-test-02:2181"
            - name: KAFKA_PORT
              value: '9092'
            - name: KAFKA_HOST
              value: "kafka-kafka.kafka-test-02"
            - name: MYSQL_DBNAME
              value: "defaultdb"
            - name: MYSQL_URL
              value: "mysql.nexclipper:3306"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: INFLUXDB_DATASOURCE
              value: "nexclipper"
            - name: REDIS_HOST
              value: redis.nexclipper
            - name: REDIS_PORT
              value: '6379'
            - name: INFLUXDB_ENDPOINT
              value: "http://influx.nexclipper:8087"
            - name: INFLUXDB_DATASOURCE
              value: "nexclipper"
            - name: BILLING_ENDPOINT
              value: "billing-meter.nexclipper:8080"
