 apiVersion: v1
 kind: Service
 metadata:
   name: shiny
   namespace: nexclipper
 spec:
   ports:
   - name: "3838"
     port: 3838
     targetPort: 3838
     name: http
   externalIPs:
   - 192.168.0.171
   selector:
     app: shiny
     type: NodePort

