apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexrouter
  labels: 
    app: nexrouter
    version: v1
  namespace: nexclipper-saas
spec:
  replicas: 1
  template:
    metadata:
      name: nexrouter
      labels:
        app: nexrouter
    spec:
      containers:
        - name: nexrouter
          image: nexclipper/nexrouter:k8s-v0.1
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          ports:
            - containerPort: 8770
              name: nexrouter
          imagePullPolicy: Always
          env:
            - name: DEFAULT_ZONE
              value: "http://localhost:8770/eureka/"
            - name: EUREKA_ENDPOINT
              value: "http://localhost:8770/eureka/apps"
            - name: CLUSTER_MODEL
              value: "K8S"
            - name: REDIS_HOST
              value: "redis.nexclipper-saas"
            - name: REDIS_PORT
              value: '6379'
            - name: ROUTER_DNS
              value: "nexcloud_nexoauth2#auth.nexclipper-saas:10100,nexcloud_nexclipperui#nexclipper-ui.nexclipper-saas:10100,nexcloud_collector#collector.nexclipper-saas:10100"
