apiVersion: v1
kind: Service
metadata:
  name: nexrouter
  labels: 
    app: nexrouter
    version: v0.1
  namespace: nexclipper-saas
spec:
  type: NodePort
  ports:
  - port: 8770
    protocol: TCP
    targetPort: 8770
    name: http
  selector:  
    app: nexrouter

