apiVersion: v1
kind: Service
metadata:
  name: auth
  labels: 
    app: auth
    version: v0.1
  namespace: nexclipper
spec:
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 8888
    name: http
  selector:  
    app: auth

