apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: host
  labels: 
    app: host
    version: v1
  namespace: nexclipper
spec:
  replicas: 1
  template:
    metadata:
      name: host
      labels:
        app: host
    spec:
      containers:
        - name: hosthapi
          image: nexclipper/host:k8s-v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: hostapi
          env:
            - name: INFLUXDB_ENDPOINT
              value: "http://influx.nexclipper:8087"
            - name: INFLUXDB_DATASOURCE
              value: "nexclipper"
            - name: REDIS_ENDPOINT
              value: redis.nexclipper
            - name: REDIS_PORT
              value: '6379'
