apiVersion: v1
kind: Service
metadata:
  name: billing-kaui
  namespace: nexclipper
  labels:
    app: billing-kaui
spec:
  type: NodePort
  ports:
  - nodePort: 32003
    port: 8080
  selector:
    app: billing-kaui
