apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexclipper
  labels: 
    app: nexclipper
    version: v1
  namespace: nexclipper
spec:
  replicas: 1
  template:
    metadata:
      name: nexclipper
      labels:
        app: nexclipper
    spec:
      containers:
        - name: nexclipperapi
          image: nexclipper/nexclipper:v0.001
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
              name: nexclipperapi
