apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: billing-meter
  namespace: nexclipper
  labels:
    app: billing-meter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-meter
    spec:
      containers:
      - name: billing-meter
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi

        image: nexclipper/meter:v1
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name:  KILLBILL_PASSWORD
          value: password
        - name:  KILLBILL_URL
          value: http://billing-kb.nexclipper:10100
        - name:  SPRING_INFLUXDB_DATABASE
          value: meter
        - name:  SPRING_DATASOURCE_PASSWORD
          value: killbill
        - name:  SPRING_REDIS
          value: redis.nexclipper:6379
        - name:  SPRING_INFLUXDB_URL
          value: http://influx.nexclipper:8087
        - name:  KILLBILL_APISECRET
          value: password
        - name:  KILLBILL_USERNAME
          value: admin
        - name:  KILLBILL_APIKEY
          value: admin
        - name:  SPRING_DATASOURCE_URL
          value: jdbc:mysql://billing-db.nexclipper:3306/killbill
        - name:  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka-kafka.kafka:9092
        ports:
        - name: kb
          containerPort: 8080

