apiVersion: v1
kind: Service
metadata:
  name: billing-meter
  namespace: nexclipper
  labels:
    app: billing-meter
spec:
  type: NodePort
  ports:
  - nodePort: 32004
    port: 8080
  selector:
    app: billing-meter
