apiVersion: v1
kind: Service
metadata:
  name: nexclipper-ui
  labels: 
    app: nexclipper-ui
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 9000
    name: http
  externalIPs:
  - 192.168.0.174
  selector:  
    app: nexclipper-ui

