 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: kube-nexclipper
   namespace: nexclipper
   annotations:
     nginx.igress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - host: kube.nexclipper.com
     http:
       paths:
       - path: /*
         backend:
           serviceName: servicegate
           servicePort: 9999

