apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: billing-kb
  namespace: nexclipper
  labels:
    app: billing-kb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-kb
    spec:
      containers:
      - name: billing-kb
        image: sppark/killbill:0.20.2
        env:
        - name: KILLBILL_DAO_URL
          value: jdbc:mysql://billing-db.nexclipper:32001/killbill
        - name: KILLBILL_DAO_USER
          value: root
        - name: KILLBILL_DAO_PASSWORD
          value: killbill
        - name: TEST_MODE
          value: "false"
        ports:
        - name: kb
          containerPort: 8080

