apiVersion: v1
kind: Service
metadata:
  name: billing-kb
  namespace: nexclipper
  labels:
    app: billing-kb
spec:
  type: NodePort
  ports:
  - nodePort: 32002
    port: 8080
  selector:
    app: billing-kb
