apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collectorapi
  labels: 
    app: collectorapi
    version: v1
  namespace: opensource
spec:
  replicas: 2
  template:
    metadata:
      name: collectorapi
      labels:
        app: collectorapi
    spec:
      containers:
        - name: collectorapi
          image: nexclipper/collectorapi:k8s
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: collectorapi
          env:
            - name: KAFKA_ZOOKEEPER
              value: "kafka-zookeeper.kafka-test-02:2181"
            - name: KAFKA_PORT
              value: '9092'
            - name: KAFKA_HOST
              value: "kafka-kafka.kafka-test-02"
            - name: MYSQL_DBNAME
              value: "defaultdb"
            - name: MYSQL_URL
              value: "mysql.opensource:3306"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: REDIS_HOST
              value: redis.opensource
            - name: REDIS_PORT
              value: '6379'
            - name: INFLUXDB_ENDPOINT
              value: http://influx.opensource:8087
            - name: INFLUXDB_DATASOURCE
              value: nexclipper
            - name: TDB
              value: ALL
            - name: PUSHGATEWAY_ENDPOINT
              value: prometheus-h-pushgateway.prometheus:9091
