---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nexclipper
  namespace: opensource
  labels:
    app: nexclipper
spec:
  selector:
    matchLabels:
      name: nexclipper
  template:
    metadata:
      labels:
        name: nexclipper
    spec:
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: log
        hostPath:
          path: /var/log
      - name: pki
        hostPath:
          path: /etc/kubernetes/pki
      hostNetwork: true
      hostPID: true
      hostIPC: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      - operator: Exists
        effect: NoExecute
        key: node-role.kubernetes.io/master
      containers:
      - name: nexclipper
        image: nexclipper/opensourceagent:k8s
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 512Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: agent_endpoint
          value: 192.168.0.180:30960
        - name: k8s_apiserver_protocol
          value: https
        - name: k8s_apiserver_port
          value: '6443'
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /var/lib/docker
          name: docker
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /var/log
          name: log
        - mountPath: /pki
          name: pki

