apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: billing-db
  namespace: nexclipper
  labels:
    app: billing-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      containers:
      - name: billing-db
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi

        image: killbill/mariadb:0.20
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: killbill
        ports:
        - name: mysql
          containerPort: 3306
