apiVersion: v1
kind: Service
metadata:
  name: billing-db-service
  namespace: nexclipper
  labels:
    app: billing-db-service
spec:
  type: NodePort
  ports:
  - nodePort: 32001
    port: 3306
  selector:
    app: billing-db-pod
