apiVersion: v1
kind: Service
metadata:
  name: collector
  labels: 
    app: collector
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    targetPort: 9000
    protocol: TCP
    name: http
  selector:  
    app: collector
