apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collector
  labels: 
    app: collector
    version: v1
  namespace: nexclipper-saas
spec:
  replicas: 2
  template:
    metadata:
      name: collector
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: nexclipper/nexcollector:k8s-v0.1
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 600Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: collector
          env:
            - name: KAFKA_ZOOKEEPER
              value: "kafka-zookeeper.kafka-test-02:2181"
            - name: KAFKA_PORT
              value: '9092'
            - name: KAFKA_HOST
              value: "kafka-kafka.kafka-test-02"
            - name: MYSQL_DBNAME
              value: "defaultdb"
            - name: MYSQL_URL
              value: "mysql.nexclipper-saas:3306"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_USERNAME
              value: "admin"
            - name: INFLUXDB_DATASOURCE
              value: "nexclipper"
            - name: REDIS_HOST
              value: redis.nexclipper-saas
            - name: REDIS_PORT
              value: '6379'
